Controllers/CarController.cs
using CloudinaryDotNet.Actions;
using CloudinaryDotNet;
using HajurKoCarRental.Data;
using HajurKoCarRental.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Principal;
using CloudinaryDotNet.Actions;
using CloudinaryDotNet;
using Microsoft.AspNetCore.Identity;

namespace HajurKoCarRental.Controllers
{
    public class CarController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;


        public CarController(ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(string filter)
        {
            IEnumerable<Car> objCarList;
            if (!User.Identity.IsAuthenticated)
            {
                filter = "all";
            }


            switch (filter)
            {
                case "all":
                    objCarList = await _db.Cars.Include(c => c.Offers).ToListAsync();
                    break;
                case "available":
                    objCarList = await _db.Cars
                    .Include(c => c.Offers)
                    .Where(c => c.IsAvailable)
                    .ToListAsync();
                    break;
                case "rent":
                    objCarList = await _db.Cars.Where(c => !c.IsAvailable).Include(c => c.Offers).ToListAsync();
                    break;
                case "frequent":
                    objCarList = await _db.RentalRequests
                        .GroupBy(r => r.CarID)
                        .Where(g => g.Count() > 3)
                        .Select(g => g.FirstOrDefault().Car)
                        .ToListAsync();
                    break;
                case "notrented":
                    objCarList = await _db.Cars
                        .Where(c => !c.RentalRequests.Any())
                        .ToListAsync();
                    break;
                default:
                    objCarList = await _db.Cars
                     .Include(c => c.Offers)
                     .Where(c => c.IsAvailable)
                     .ToListAsync();
                    break;
            }

            return View(objCarList);
        }

        public IActionResult TableCarView()
        {
            IEnumerable<Car> objCarList = _db.Cars;
            return View(objCarList);
        }
        public IActionResult Create()
        {
            return View();
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car obj, IFormFile file)
        {
            var account = new Account(
                "NabinNs",
                "428542427551857",
                "A1gFD-djrOGlzEhYe-ysX_A2JUo");
            var cloudinary = new Cloudinary(account);

            var uploadResult = new ImageUploadResult();
            if (file != null && file.Length > 0)
            {
                var uploadParams = new ImageUploadParams
                {
                    File = new FileDescription(file.FileName, file.OpenReadStream())
                };

               uploadResult = await cloudinary.UploadAsync(uploadParams);

            }

            var car = new Car
            {
                Manufacturer = obj.Manufacturer,
                Model = obj.Model,
                RentalRate = obj.RentalRate,
                VehicleNo = obj.VehicleNo,
                IsAvailable = obj.IsAvailable,
                Color = obj.Color,
                CarImageUrl = uploadResult.SecureUrl?.ToString()
            };
            _db.Cars.Add(car);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        //_db.Cars.Add(obj);
        //_db.SaveChanges();
        //return RedirectToAction("Index");


        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var carFromDb = _db.Cars.Find(id);
            if (carFromDb == null)
            {
                return NotFound();
            }
            return View(carFromDb);
        }
        //Post
        [HttpPost]
        public IActionResult Edit(Car car)
        {

            var carFromDb = _db.Cars.Find(car.CarID); // Find the existing car object from the database
            if (carFromDb != null)
            {
                carFromDb.Manufacturer = car.Manufacturer; // Update the car properties with the new values
                carFromDb.Model = car.Model;
                carFromDb.Color = car.Color;
                carFromDb.RentalRate = car.RentalRate;
                carFromDb.VehicleNo = car.VehicleNo;
                carFromDb.IsAvailable = car.IsAvailable;
                carFromDb.CarImageUrl = car.CarImageUrl;

                _db.Cars.Update(carFromDb); // Update the car object in the database
                _db.SaveChanges();

                return RedirectToAction("Index"); // Redirect to the index action
            }

            return NotFound(); // Car
        }
        public IActionResult Delete(int? id)
        {
            var obj = _db.Cars.Find(id);
            if (id == null || id == 0)
            {
                return NotFound();
            }
            if (obj == null)
            {
                return NotFound();
            }
            _db.Cars.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult ViewCar(int? id)
        {
            var carFromDb = _db.Cars.Find(id);
            if (carFromDb == null)
            {
                return NotFound();
            }

            return View(carFromDb);
        }


    }
}

Controllers/DamageController.cs
using HajurKoCarRental.Data;
using HajurKoCarRental.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HajurKoCarRental.Controllers
{
    public class DamageController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DamageController(ApplicationDbContext db)
        {
            _db = db;
        }
        [Authorize(Roles = "Admin,Staff")]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Damage> allDamages = await _db.Damages
                .Include(d => d.Car)
                .Include(d => d.User)
                .ToListAsync();

            return View(allDamages);
        }

    }
}

Controllers/OfferController.cs
using HajurKoCarRental.Data;
using HajurKoCarRental.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HajurKoCarRental.Controllers
{
    public class OfferController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailSender _emailSender;
       
        public OfferController(ApplicationDbContext db, UserManager<IdentityUser> userManager, IEmailSender emailSender)
        {
            _db = db;
            _userManager = userManager;
            _emailSender = emailSender;
        }
        [Authorize(Roles = "Admin,Staff")]
        public IActionResult Index()
        {
            var offerlist = _db.Offers.Include(o => o.Car).ToList();
            //IEnumerable<Offer> offerlist = _db.Offers;
            return View(offerlist);
        }
        [Authorize(Roles = "Admin,Staff")]
        public async Task<ActionResult> CreateOffer()
        {
            //var cars = await _db.Cars.Select(c => new { ID = c.CarID, Name = c.Model + "-" + c.Color }).ToListAsync();
            //ViewBag.CarID = new SelectList(cars, "ID", "Name");
            //return View();
            IEnumerable<Car> CarList = _db.Cars;
            return View(CarList);
        }

        //Post
        [HttpPost]
        public async Task<ActionResult> AddOffer()
        {
            string carId = Request.Form["carId"];
            string discountRate = Request.Form["DiscountRate"];
            string endDate = Request.Form["EndDate"];
            string offerDescription = Request.Form["OfferDescription"];

            // Check if there is an existing offer for the car with status true
            var existingOffer = await _db.Offers.FirstOrDefaultAsync(o => o.CarID == int.Parse(carId) && o.Status == true);

            // If there is an existing offer, update its status to false
            if (existingOffer != null)
            {
                existingOffer.Status = false;
                _db.Entry(existingOffer).State = EntityState.Modified;
                await _db.SaveChangesAsync();
            }

            Offer offer = new Offer()
            {
                CarID = int.Parse(carId),
                DiscountRate = decimal.Parse(discountRate),
                EndDate = DateTime.Parse(endDate),
                OfferDescription = offerDescription,
                Status = true
            };

            // add the offer to the database
            _db.Offers.Add(offer);
            _db.SaveChanges();

            var customers = await _userManager.GetUsersInRoleAsync("Customer");
            var car = await _db.Cars.FindAsync(int.Parse(carId));
            foreach(var customer in customers)
            {
                var applicationUser = customer as ApplicationUser;
                var subject = "New Offer";
                var message = $@"
            <html>
                <body>
                    <p>Dear {applicationUser.Name},</p>
                    <p>A new offer is now available for the following car:</p>
                  <img src='{car.CarImageUrl}' alt='Image description' style='width: 300px; height: 200px; object-fit: cover;'>
                    <p><strong>{car.Manufacturer} {car.Model} ({car.Color})</strong></p>
                    <p>Offer Details: {offer.OfferDescription}</p>
                    <p>Thank you for using our services!</p>
                </body>
            </html>";
                await _emailSender.SendEmailAsync(customer.Email, subject, message);
            }
            return RedirectToAction("Index", "Car");

        }
        [Authorize(Roles = "Admin,Staff")]
        public IActionResult Delete(int? id)
        {
            var obj = _db.Offers.Find(id);
            if (id == null || id == 0)
            {
                return NotFound();
            }
            if (obj == null)
            {
                return NotFound();
            }
            _db.Offers.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin,Staff")]
        public IActionResult CloseOffer(int? id)
        {
            var offerData = _db.Offers.Find(id);
            if (id == null || id == 0)
            {
                return NotFound();
            }
            if (offerData == null)
            {
                return NotFound();
            }
            offerData.Status = false; // Update the offer status to false
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Controllers/UserController.cs
using HajurKoCarRental.Areas.Identity.Pages.Account;
using HajurKoCarRental.Data;
using HajurKoCarRental.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using System.Diagnostics;

namespace HajurKoCarRental.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RegisterModel _registerModel;


        public UserController(ApplicationDbContext db, UserManager<IdentityUser> userManager, RegisterModel registerModel)
        {
            _db = db;
            _userManager = userManager;
            _registerModel = registerModel;
        }
        public IActionResult Index()
        {
           
            IEnumerable<ApplicationUser> userList = _db.Set<ApplicationUser>();

            return View(userList);
        }

        public IActionResult EditUserDetail (string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var userFromDb = _db.ApplicationUsers.SingleOrDefault(u => u.Id == id);

            if (userFromDb == null)
            {
                return NotFound();
            }

            return View(userFromDb);
        }
        //Post
        [HttpPost]
        public async Task<IActionResult> EditUserDetail(ApplicationUser user)
        {
                var userFromDb = _db.ApplicationUsers.FirstOrDefault(u => u.Id == user.Id);

                if (userFromDb == null)
                {
                    return NotFound();
                }

                userFromDb.Name = user.Name;
                userFromDb.Email = user.Email;
                userFromDb.PhoneNumber = user.PhoneNumber;

                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }
        //Post
        [HttpPost]

        public async Task<IActionResult> UpdatePassword(string userId, string newPassword, string confirmPassword)
        {


            var userFromDb = _db.ApplicationUsers.FirstOrDefault(u => u.Id == userId);

            if (userFromDb == null)
            {
                return NotFound();
            }

            if (newPassword != confirmPassword)
            {
                ModelState.AddModelError("Error", "The new password and confirmation password do not match.");
                return RedirectToAction("Index");
            }

            var passwordHasher = new PasswordHasher<ApplicationUser>();
            var hashedPassword = passwordHasher.HashPassword(userFromDb, newPassword);
            userFromDb.PasswordHash = hashedPassword;

            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        public IActionResult Delete(string id)
        {
            var obj = _db.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if (id == null || obj == null)
            {
                return NotFound();
            }

            _db.ApplicationUsers.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddDocument()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            return View(currentUser);
        }

        [HttpPost]
        public async Task<IActionResult> AddDocumentToDB(IFormFile DrivingLicense, IFormFile Citizenship)
        {
            var user = await _userManager.GetUserAsync(User) as ApplicationUser;
            if ((Citizenship?.Length ?? 0) > 1572864 || (DrivingLicense?.Length ?? 0) > 1572864)
            {
                ModelState.AddModelError(string.Empty, "The size of the  photo must not be more than 1.5 MB.");
                return RedirectToAction("AddDocument");
            }

            user.Verified = Citizenship != null || DrivingLicense != null;

            if (Citizenship != null)
            {
                string citizenshipUrl = await _registerModel.SaveDocumentPhoto(Citizenship, user.Name, "Citizenship");

                user.CitizenshipURL = citizenshipUrl;
            }
            if (DrivingLicense != null)
            {
                //string licenseUrl = await SaveDocumentPhoto(DrivingLicense, user.Name, "License");

                string licenseUrl = await _registerModel.SaveDocumentPhoto(DrivingLicense, user.Name, "License");
                user.DrivingLicenseURL = licenseUrl;
            }
            await _userManager.UpdateAsync(user);


            return RedirectToAction("Index", "Car");
        }




    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HajurKoCarRental</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HajurKoCarRental.styles.css" asp-append-version="true" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
    @*CDN datatable*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
    @*slick cdn*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css" />
    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow ">
            <div class="container-fluid">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HajurKoCarRental</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="d-flex justify-content-center">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
  
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Car"  asp-action="Index">Cars</a>
                            </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin")){
                   
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User Control</a>
                            </li>
                            }
                            if (User.IsInRole("Admin") || User.IsInRole("Staff")){
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Offer" asp-action="Index">Offer</a>
                            </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Damage" asp-action="Index">Damage</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="RentalData" asp-action="Index">Rental Requests</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="RentalData" asp-action="RentalHistory">Rental Histories</a>
                            </li>
                            @if (User.IsInRole("Customer"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="RentalData" asp-action="CustomerBill">Bills</a>
                                </li>
                            }
                        }
                    </ul>
               </div>
               </div>
               <div>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2023 - HajurKoCarRental - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>





  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    @*Sweet alert cdn*@
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


    <script>
        let sidebar = document.querySelector(".sidebar");
        let sidebarBtn = document.querySelector(".bx-menu");
        sidebarBtn.addEventListener("click", () => {
            sidebar.classList.toggle("close");
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_UnregisteredLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HajurKoCarRental</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HajurKoCarRental.styles.css" asp-append-version="true" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
    @*CDN datatable*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
    

</head>
<body>
    <section>
        @RenderBody()
        </section>






  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*Sweet alert cdn*@
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


    <script>
        let sidebar = document.querySelector(".sidebar");
        let sidebarBtn = document.querySelector(".bx-menu");
        sidebarBtn.addEventListener("click", () => {
            sidebar.classList.toggle("close");
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>