Models/RentalHistory.cs
//using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;

//namespace HajurKoCarRental.Models
//{
//    public class RentalHistory
//    {
//        [Key] public int RentalID { get; set; }
//        [ForeignKey("Id")] public string UserID { get; set; }
//        [ForeignKey("CarID")] public int CarID { get; set; }
//        public DateTime RentalDate { get; set; }
//        [ForeignKey("Id")] public string? AuthorizedByID { get; set; }
//        public virtual ApplicationUser User { get; set; }
//        public virtual Car Car { get; set; }
//        public virtual ApplicationUser AuthorizedBy { get; set; }
//        public virtual RentalRequest RentalRequest { get; set; }
//    }
//}

Controllers/RentalDataController.cs
using HajurKoCarRental.Data;
using HajurKoCarRental.Models;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace HajurKoCarRental.Controllers
{
    public class RentalDataController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailSender _emailSender;

        public RentalDataController(ApplicationDbContext db, UserManager<IdentityUser> userManager, IEmailSender emailSender)
        {
            _db = db;
            _userManager = userManager;
            _emailSender = emailSender;

        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound();
            }

            var userType = await _userManager.GetRolesAsync(user);

            IQueryable<RentalRequest> rentalRequestsQuery = _db.RentalRequests
                .Include(r => r.User)
                .Include(r => r.Car);

            if (userType.Contains("Customer"))
            {
                rentalRequestsQuery = rentalRequestsQuery.Where(r => r.User.Id == user.Id && (r.Status == "Approved" || r.Status == "Pending"));
            }
            else if (userType.Contains("Admin") || userType.Contains("Staff"))
            {
                rentalRequestsQuery = rentalRequestsQuery.Where(r => r.Status == "Pending" || r.Status == "Canceled Pending" || r.Status == "Return Pending");
            }

            var rentalRequests = await rentalRequestsQuery.ToListAsync();

            return View(rentalRequests);
        }
        [Authorize]
        public async Task<IActionResult> RentalHistory(DateTime? startDate, DateTime? endDate)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound();
            }

            var userType = await _userManager.GetRolesAsync(user);

            IQueryable<RentalRequest> rentalRequestsQuery = _db.RentalRequests
                .Include(r => r.User)
                .Include(r => r.Car)
                .Include(r => r.AuthorizedByUser);
            if (startDate != null && endDate != null)
            {
                //filter according to date match of request date
                rentalRequestsQuery = rentalRequestsQuery.Where(r => r.RequestDate >= startDate && r.RequestDate <= endDate);
            }

            if (userType.Contains("Customer"))
            {
                rentalRequestsQuery = rentalRequestsQuery.Where(r => r.User.Id == user.Id);
            }

            var rentalRequests = await rentalRequestsQuery.ToListAsync();

            return View(rentalRequests);

    
        }
        [Authorize]
        public async Task<IActionResult> CustomerBill()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound();
            }

            IQueryable<RentalRequest> rentalRequestsQuery = _db.RentalRequests
                .Include(r => r.User)
                .Include(r => r.Car)
                .Include(r => r.Damages)
                .Where(r => r.User.Id == user.Id && r.Paid != null);

            var rentalRequests = await rentalRequestsQuery.ToListAsync();

            return View(rentalRequests);
        }

    }
}

Controllers/RequestCarController.cs
using HajurKoCarRental.Data;
using HajurKoCarRental.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Net.Mail;
using System.Runtime.ConstrainedExecution;
using System.Security.Claims;

namespace HajurKoCarRental.Controllers
{
    public class RequestCarController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailSender _emailSender;

        public RequestCarController(ApplicationDbContext db, UserManager<IdentityUser> userManager, IEmailSender emailSender)
        {
            _db = db;
            _userManager = userManager;
            _emailSender = emailSender;

        }


        public async Task<IActionResult> Index()
        {
   

            IEnumerable<Car> CarList = _db.Cars.Where(c => c.IsAvailable == true);
            return View(CarList);

        }

        [Authorize]
        public async Task<IActionResult> AddRequestCar(int id, decimal? dis)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId) as ApplicationUser;

            if (user != null)
            {
                var forpaymentrentaldata = await _db.RentalRequests.Where(r => r.UserID == user.Id).ToListAsync();
                bool anyNotPaid = forpaymentrentaldata.Any(r => r.Paid == false);
                user.PaymentDue = anyNotPaid;
                await _db.SaveChangesAsync();
            }
            if (user.Verified != true)
            {
                return BadRequest("Citizenship and license is required.");
            }
            if (user.PaymentDue == true)
            {
                return BadRequest("Payment needs to be cleared before requesting renting.");
            }


            // Check if the carId is valid
            var car = _db.Cars.FirstOrDefault(c => c.CarID == id);
            if (car == null)
            {
                // Return an error message to the user

                return BadRequest("Invalid CarID");
            }
            //so that other cannot request same car again
            car.IsAvailable = false;
            _db.Cars.Update(car);


            // Create a new rental request with the given car ID and user ID
            var requestForRent = new RentalRequest
            {
                CarID = id,
                UserID = userId,
                RequestDate = DateTime.Now,
                Status = "Pending",
                OfferDis = dis
            };

            // Add the rental request to the database
            _db.RentalRequests.Add(requestForRent);
            await _db.SaveChangesAsync();



            return RedirectToAction("Index", "Car");

        }


        //Request handler for Admin and staff to approve or reject request
        public async Task<IActionResult> RequestHandler(int id, string status)
        {
            // Find the rental request by ID
            var rentalRequest = await _db.RentalRequests.Include(r => r.Car).FirstOrDefaultAsync(r => r.ReqID == id);

            if (rentalRequest == null)
            {
                return BadRequest("Invalid Rental Request ID");  // Return an error message to the user
            }
            //current user logged in id
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            // Update the rental request status
            rentalRequest.Status = status;
            rentalRequest.AuthorizedBy = userId;
            if (status == "Rejected")
            {
                rentalRequest.Car.IsAvailable = true;
            }
            _db.RentalRequests.Update(rentalRequest);
            await _db.SaveChangesAsync();

            if (status == "Approved" || status == "Canceled" || status == "Rejected" || status == "Returned")
            {
                //send email to nootify user about their request
                var user = await _userManager.FindByIdAsync(rentalRequest.UserID);
                var applicationUser = (ApplicationUser)user;
                var emailSubject = "Rental Request Status";
                var emailBody = @$"<html>
               <head>
                   <style>
      
                    label {{
                            font-weight: bold;
                                }}
                        </style>
                    </head>
                    <body>
                        <p>Dear {applicationUser.Name},</p>
                 <img src='{rentalRequest.Car.CarImageUrl}' alt='Image description' style='width: 300px; height: 200px; object-fit: cover;'>
                        <p>Your rental request for:</p>
                        <ul>
                            <li>
                                <label>Manufacturer: </label> {rentalRequest.Car.Manufacturer}
                            </li>
                            <li>
                                <label>Model: </label> {rentalRequest.Car.Model}
                            </li>
                            <li>
                                <label>Color: </label> {rentalRequest.Car.Color}
                            </li>
                            <li>
                                <label>Vehicle: </label> {rentalRequest.Car.VehicleNo}
                                  </li>
                             </ul>
                            <p>has been {status}.</p>
                         <p>Thank you,</p>
                        <p>The Car Rental Team</p>
                    </body>
                    </html>";
                await _emailSender.SendEmailAsync(user.Email, emailSubject, emailBody);
            }
            return RedirectToAction("Index", "RentalData");
        }



        //Request handler for customer to either return or cancel request
        public async Task<IActionResult> CustomerRequestHandler(int id, string status)
        {
            // Find the rental request by ID
            var rentalRequest = await _db.RentalRequests.Include(r => r.Car).FirstOrDefaultAsync(r => r.ReqID == id);

            if (rentalRequest == null)
            {
                return BadRequest("Invalid Rental Request ID");  // Return an error message to the user
            }
            //current user logged in id
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            rentalRequest.Car.IsAvailable = true; // update car status aftering canceling request
            // Update the rental request status
            rentalRequest.Status = status;
            rentalRequest.ReturnDate = DateTime.Now;
            _db.RentalRequests.Update(rentalRequest);
            await _db.SaveChangesAsync();

            //var staffs = await _userManager.GetUsersInRoleAsync("Staff");
            //foreach (var staff in staffs)
            //{
            //    var subject = "New Offer";
            //    var message = "Dear staffs, A new request has been made.";
            //    await _emailSender.SendEmailAsync(staff.Email, subject, message);
            //}
            return RedirectToAction("Index", "RentalData");
        }


        //Request handler for Admin and staff to  reject request
        public async Task<IActionResult> RequestCancelHandler(int id, string status)
        {
            // Find the rental request by ID
            var rentalRequest = await _db.RentalRequests.Include(r => r.Car).FirstOrDefaultAsync(r => r.ReqID == id);

            if (rentalRequest == null)
            {
                return BadRequest("Invalid Rental Request ID");  // Return an error message to the user
            }
            //current user logged in id
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            // Update the rental request status
            rentalRequest.Status = status;
            rentalRequest.AuthorizedBy = userId;
            _db.RentalRequests.Update(rentalRequest);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index", "RentalData");
        }


        //handle return request by customer
        [HttpPost]
        public async Task<IActionResult> ReturnCustomerHandler()
        {
            var rentalId = Request.Form["rentalId"];
            int id = int.Parse(rentalId);
            // Find the rental request by ID
            var rentalRequest = await _db.RentalRequests.Include(r => r.Car).FirstOrDefaultAsync(r => r.ReqID == id);

            if (rentalRequest == null)
            {
                return BadRequest("Invalid Rental Request ID");  // Return an error message to the user
            }

            string damage = Request.Form["Damage"];
            string damageDescription = Request.Form["DamageDescription"];
            string damageType = Request.Form["DamageType"];
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Update the rental request status
            rentalRequest.Status = "Return Pending";
            rentalRequest.ReturnDate = DateTime.Now;
            rentalRequest.damage = damage;
            rentalRequest.Car.IsAvailable = true;
            if (damage == "true")
            {
                // Create a new instance of Damage
                var damageRecord = new Damage
                {
                    UserID = userId,
                    CarID = rentalRequest.Car.CarID,
                    RentalID = rentalRequest.ReqID,
                    DamageDescription = damageDescription,
                    DamageType = damageType
                    
                };

                // Add the damage record to the context and save changes
                _db.Damages.Add(damageRecord);
                await _db.SaveChangesAsync();
            }

Views/RentalData/CustomerBill.cshtml
@model List<RentalRequest>

    @*to display pending bills of customers
        on can be viewed by customer --> customer page
    *@
@{
    ViewData["Title"] = "Customer Bill";
}
<style>
    .dataTables_wrapper{
        margin: 10px 10px 10px 10px;
    }
</style>


<div class="d-flex justify-content-center align-items-center h-100">
    <div class="container">
        <div class="card shadow-lg">
            <div class="card-header">
                <h4 class="fw-bold mb-0 text-center">Bills List</h4>
            </div>

       

    <table class="table" id="table-bill">
        <thead>
            <tr>
                <th>Model</th>
                <th>Vehicle No</th>
                <th>Request Date</th>
                <th>Return Date</th>
                <th>Authorized By</th>
                <th>Damaged</th>
                <th>Damaged Type</th>
               <th>Total Amount</th>
               <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var rentalRequest in Model)
            {
                 <tr class="@(rentalRequest.Paid == true ? "text-success" : "text-danger")">
                    <td>@rentalRequest.Car.Model</td>
                    <td>@rentalRequest.Car.VehicleNo</td>
                    <td>@rentalRequest.RequestDate.ToShortDateString()</td>
                    <td>@(rentalRequest.ReturnDate?.ToShortDateString() ?? "N/A")</td>
                    <td>@(rentalRequest.AuthorizedByUser != null ? rentalRequest.AuthorizedByUser.Name : "N/A")</td>
                    <td>@(String.Equals(rentalRequest.damage, "true", StringComparison.OrdinalIgnoreCase) ? "Yes" : "No")</td>
                     <td>@(rentalRequest.Damages.FirstOrDefault()?.DamageType ?? "No Damage")</td>
                     <td>@rentalRequest.TotalAmount</td>
                   
                     <td>
                        @if (rentalRequest.Paid == false)
                         {
                        <a asp-controller="RequestCar" asp-action="PayDue" asp-route-id=@rentalRequest.ReqID class="btn btn-success">Pay</a>
                         }
                         else{
                                    <i class="fas fa-check ms-3"></i>
                         }
                     </td>
                          

                </tr>
            }
        </tbody>
    </table>


        </div>
    </div>
</div>



@section Scripts{

    <script>
        $(document).ready(function () {
            $('#table-bill').DataTable();
       
        });
    </script>

}
@*<a asp-controller="RequestCar" asp-action="AddRequestCar" asp-route-id="@rentalRequest.ReqID" class="btn btn-success">Approve</a>
<a asp-controller="RequestCar" asp-action="AddRequestCar" asp-route-id="@rentalRequest.ReqID" class="btn btn-danger">Reject</a>*@

Views/RentalData/Index.cshtml
@model List<RentalRequest>

@{
    ViewData["Title"] = "Car Request";
}
<style>
    .dataTables_wrapper{
        margin: 10px 10px 10px 10px;
    }
</style>

<div class="d-flex justify-content-center align-items-center h-100">
    <div class="container">
        <div class="card shadow-lg">
            <div class="card-header">
                <h4 class="fw-bold mb-0 text-center">Rental Requests Action</h4>
            </div>

@if (User.IsInRole("Customer"))
{
    <table class="table" id="customerRequest">
        <thead>
            <tr>
                <th>Brand</th>
                <th>Model</th>
                <th>Vehicle No</th>
                <th>Request Date</th>
                <th>Status</th>
                <th>Action</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var rentalRequest in Model)
            {
                <tr>
                    <td>@rentalRequest.Car.Manufacturer </td>
                    <td>@rentalRequest.Car.Model</td>
                    <td>@rentalRequest.Car.VehicleNo</td>
                    <td>@rentalRequest.RequestDate</td>
                    <td>@rentalRequest.Status</td>
                    <td>
                        @if (rentalRequest.Status == "Approved")
                        {
                            <button class="btn btn-success" type="button" data-bs-toggle="modal"
                        data-bs-target="#CustomerReturnModal" onclick="setCustomerReturnId('@rentalRequest.ReqID')">
                                Return
                            </button>
                        }
                        <a asp-controller="RequestCar" asp-action="CustomerRequestHandler" asp-route-id="@rentalRequest.ReqID" asp-route-status="Canceled Pending" class="btn btn-danger">Cancel</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

else if (User.IsInRole("Admin") || User.IsInRole("Staff"))
{
            
    <div class="d-flex justify-content-center mt-3">
        <h5 class="me-4 mb-5 setting-heading setting-pointer" data-target="table-pending">Pending Requests</h5>
        <h5 class="mb-5 setting-pointer" data-target="table-canceled">Return Requests</h5>
    </div>

    <table class="table" id="table-pending">
        <thead>
            <tr>
                <th>Brand</th>
                <th>Model</th>
                <th>Vehicle No</th>
                <th>User Name</th>
                <th>Regular</th>
                <th>Request Date</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody class="text-success">
            @foreach (var rentalRequest in Model.Where(r => r.Status == "Pending"))
            {
                <tr>
                    <td>@rentalRequest.Car.Manufacturer</td>
                    <td>@rentalRequest.Car.Model</td>
                    <td>@rentalRequest.Car.VehicleNo</td>
                    <td>@rentalRequest.User.Name</td>
                    
                    <td>@(rentalRequest.User.IsRegular ? "Yes" : "No")</td>
                    <td>@rentalRequest.RequestDate.ToShortDateString()</td>
                    <td>@rentalRequest.Status</td>
                    <td>
                        <a asp-controller="RequestCar" asp-action="RequestHandler" asp-route-id="@rentalRequest.ReqID" asp-route-status="Approved" class="btn btn-success">Approve</a>
                        <a asp-controller="RequestCar" asp-action="RequestHandler" asp-route-id="@rentalRequest.ReqID" asp-route-status="Rejected" class="btn btn-danger">Reject</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>


    //table to show for canceled or return pending
    <table class="table hide" id="table-canceled">
        <thead>
            <tr>
                <th>Brand</th>
                <th>Model</th>
                <th>Vehicle No</th>
                <th>User Name</th>
                <th>Regular</th>
                <th>Request Date</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var rentalRequest in Model.Where(r => r.Status == "Canceled Pending" || r.Status == "Return Pending"))
            {
                <tr>
                    <td>@rentalRequest.Car.Manufacturer</td>
                    <td>@rentalRequest.Car.Model</td>
                    <td>@rentalRequest.Car.VehicleNo</td>
                    <td>@rentalRequest.User.Name</td>
                    <td>@(rentalRequest.User.IsRegular ? "Yes" : "No")</td>
                    <td>@rentalRequest.RequestDate.ToShortDateString()</td>
                    <td>@rentalRequest.Status</td>
                    <td>
                        @if (rentalRequest.Status == "Canceled Pending")
                        {
                            <a asp-controller="RequestCar" asp-action="RequestCancelHandler" asp-route-id="@rentalRequest.ReqID" asp-route-status="Canceled" class="btn btn-danger">Cancel</a>
                        }
                        else if (rentalRequest.Status == "Return Pending")
                        {
                            <a asp-controller="RequestCar" asp-action="ReturnProcessing" asp-route-id="@rentalRequest.ReqID" asp-route-status="Returned" class="btn btn-danger">Return</a>
                        }
                    </td>
                </tr>
            }

        </tbody>
    </table>
}
        </div>
    </div>
</div>

<!-- Return Modal for Customer detailing about return -->

<div class="modal fade" id="CustomerReturnModal" tabindex="-1" aria-labelledby="AddOfferModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center font" id="AddOfferModalLabel">Return slip</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <form method="post" action="@Url.Action("ReturnCustomerHandler", "RequestCar")">
                <div class="modal-body">
                    <input type="hidden" name="rentalId" id="IdforRental">
                    <div class="form-group">
                        <label class="form-label" for="Damage">Was there any damage?</label>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="Damage" id="DamageYes" value="true" checked>
                            <label class="form-check-label" for="DamageYes">Yes</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="Damage" id="DamageNo" value="false">
                            <label class="form-check-label" for="DamageNo">No</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-label" for="DamageType">Damage Type:</label>
                        <select class="form-select" id="DamageType" name="DamageType">
                            <option value="minor">Minor</option>
                            <option value="moderate">Moderate</option>
                            <option value="major">Major</option>
                            <option value="scratches">Scratches</option>
                            <option value="dents">Dents</option>

                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-label" for="DamageDescription">If yes, please describe:</label>
                        <input class="form-control" type="text" id="DamageDescription" name="DamageDescription" placeholder="Damage Description">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>

        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $("[data-target]").click(function () {
                var targetId = $(this).data("target");
                if (targetId === "table-pending") {
                    $("#table-pending").show();
                    $('#table-pending').DataTable({
                        "ordering": false
                    });
                    $("#table-canceled").hide();
                    $('#table-canceled').DataTable().destroy();
                } else if (targetId === "table-canceled") {
                    $("#table-pending").hide();
                    $("#table-canceled").show();
                    $('#table-canceled').DataTable({
                        "ordering": false
                    });
                    $('#table-pending').DataTable().destroy();
                }
                $("[data-target]").removeClass("setting-heading");
                $(this).addClass("setting-heading");
            });
        });

    </script>
    <script>
        $(document).ready(function () {
            $('#customerRequest').DataTable();
            $('#table-pending').DataTable(
                {
                    sorting: false
                });
           
       
        });
    </script>
    <script>
        function setCustomerReturnId(rentalId) {
            document.getElementById('IdforRental').value = rentalId;

        }
    </script>
}
@*<a asp-controller="RequestCar" asp-action="AddRequestCar" asp-route-id="@rentalRequest.ReqID" class="btn btn-success">Approve</a>
<a asp-controller="RequestCar" asp-action="AddRequestCar" asp-route-id="@rentalRequest.ReqID" class="btn btn-danger">Reject</a>*@